global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://webhook.site/2e6dc22a-f059-49f4-9375-54e92a9e7e87'
          send_resolved: false
